### ISSUE TITLE
About FCGN!!

### ISSUE THREAD

**Issue by a673660099** [mf-zhang/Optical-Flow-in-the-Dark#2]
Hi, thanks for the two great work!

I have read your"optical flow in the dark" cvpr&tpami  in detail, and I would like to ask if there is any access about FCGN?
 download link...etc.
 

very very very !!!!!!! looking forward to your reply!!!

**Comment by Geniussh** [comment]
It's well documented [here](https://github.com/mf-zhang/Optical-Flow-in-the-Dark/tree/main/FCDN_dataset) already.
FCDN = Downloading the original FlyingChairs + Postprocessing it using FCDN_Synthesize.py

**Comment by a673660099** [comment]
> It's well documented [here](https://github.com/mf-zhang/Optical-Flow-in-the-Dark/tree/main/FCDN_dataset) already. FCDN = Downloading the original FlyingChairs + Postprocessing it using FCDN_Synthesize.py

HI, Do you have finised paired VBOF dataset? There is a problem with my computer. It is urgently needed! Thank you. I hope to get your recovery~~~~~~~~~~~~~~~~~~~~~~

**Comment by mf-zhang** [comment]
Sorry that we cannot release FCGN because of the large file size.

To get the paired VBOF dataset, the released script may take too much memory(?), but I believe that we can modify the code easily to process the data in small batches.
