### ISSUE TITLE
How to analyze Gaussian and Poisson related parameters

### ISSUE THREAD

**Issue by Geniussh** [mf-zhang/Optical-Flow-in-the-Dark#3]
How did you analyze Gaussian and Poisson related parameters a and b as shown in Figure 4? 

When creating FCDN, you mentioned "randomly sample shot and read parameter a and b from ranges that match what we observe in real data", may I know how do you observe the "ranges" from real data?

I have a dataset A, and I wish to estimate its a and b so I can add noise to a clean/daylight dataset B with the same noise estimated from A.

**Comment by mf-zhang** [comment]
As cited in our paper, we employ this method https://webpages.tuni.fi/foi/sensornoise.html
